repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,W503]

  - repo: local
    hooks:
      - id: autograd-tests
        name: Run autograd tests
        entry: bash -c 'cd autograd/tests && python run_tests.py'
        language: system
        files: ^autograd/
        pass_filenames: false
        
      - id: import-tests
        name: Test module imports
        entry: python
        language: system
        args: ['-c', 'import sys; sys.path.append("autograd"); sys.path.append("lib"); sys.path.append("regression"); sys.path.append("classification"); from simple import *; from activations import *; print("✅ All imports successful")']
        files: '\.(py)$'
        pass_filenames: false